import Head from 'next/head'
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import Login from './'



export default function Home({ Session }) {
  if(!Session) return <Login />
  return (
    <div>
      <Head>
        <title>Clone Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    <Header />
    <main className="flex bg-gray-100">
      {/* leftsidebar */}
      <Sidebar />
      {/* Feed (Create Post and Posts) */}
      {/* rightsidebar */}
    </main>
  
    </div>
  )
}

export async function getServerSideProps (context){
  const session = await getSession(context);
  return{
    props: {session},
  }
}
